config/routes.rb
Rails.application.routes.draw do
  root "depts#index"
  
  resources :depts do
    resources :items

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dept.rb
class Dept < ApplicationRecord
    has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :dept
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/depts_controller.rb
class DeptsController < ApplicationController

  before_action :set_dept, only: [:show, :edit, :update, :destroy]

  def index
    @depts = Dept.all
    # render :index
  end

  def show
  end

  def new
    @dept = Dept.new
    render partial: "form"
  end

  def create
    @dept = Dept.new(dept_params)

    if @dept.save
      redirect_to dept_path(@dept.id)
    else
      render partial: "form"
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @dept.update(dept_params)
      redirect_to dept_path(@dept.id)
    else
      render partial: "form"
    end
  end

  def destroy
    @dept.destroy
    redirect_to depts_path
  end

private
  def dept_params
    params.require(:dept).permit(:category, :description, :manager, :seasonal)
  end

  def set_dept
    @dept = Dept.find(params[:id])
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_dept
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  
  
  def index
    @items = @dept.items
  end

  def show
  end

  def new
    @item = @dept.items.new
    render partial: "form"
  end

  def create
    @item= @dept.items.new(item_params)

    if @item.save
      redirect_to [@dept, @item]
    else
      render partial: "form"
    end
  end

  def edit
    render partial: "form"
  end

  def update
    if @item.update(item_params)
      redirect_to [@dept, @item]
    else
      render partial: "form"
    end
  end

  def destroy
    @item.destroy
    redirect_to dept_items_path(@dept)
  end

private 

  def set_dept
    @dept = Dept.find(params[:dept_id])
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :price, :descr)
  end
end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/depts_helper.rb
module DeptsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/depts/_form.html.erb
<<h1><h1> <%= @dept.id ? "Edit Department" : "Create Department" %> </h1>
<hr />
<%= form_for @dept do |f| %>
  <%= f.label :category %>
  <%= f.text_field :category, required: true, autofocus: true %>
  
  <%= f.label :manager %>
  <%= f.text_field :manager, required: true%>
  
  <%= f.label :description %> 
  <%= f.text_area :description, required: true%>

  <%= f.label :seasonal %>
  <%= f.check_box :seasonal %>

  <%= f.submit %>
<% end %>

app/views/depts/index.html.erb
<h1>Department Store - Select a Category To View Description</h1>
<%= link_to 'Create a New Department Category', new_dept_path %>
<ul>
  <% @depts.each do |dept| %>
    <li><%= link_to dept.category, dept_path(dept.id) %></li>
  <% end %>
</ul>

app/views/depts/show.html.erb
<h1><%= @dept.category %></h1>

<h4><%= "Description:" %><%=' '=%><%= @dept.description %></h4>
<h4><%= "Manager:" %><%=' '=%><%= @dept.manager %></h4>
<h4><%= "Seasonal?" %><%=' '=%><%= @dept.seasonal %> </h4>





<p>What would you like to do?</p>

<%= link_to 'Items', dept_items_path(@dept.id) %>
<br />
<%= link_to 'Edit Department', edit_dept_path(@dept) %>
<br />
<%= link_to 'Delete Department', dept_path(@dept.id), method: :delete %>
<br />
<br />
<%= link_to "Back to Departments", depts_path%>

app/views/items/_form.html.erb
<h1><%= @item.id ? 'Edit Item' : 'Create Item' %></h1>
<hr />
<%= form_for [@dept, @item] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <br />
  <%= f.label :price %>
  <%= f.number_field :price, required: true %>
  
  <%= f.label :descr %>
  <%= f.text_area :descr, required: true %>

  <%= f.submit %>
<% end %>

app/views/items/index.html.erb
<h1><%= "Department:" %><%=' '%> <%= @dept.category%> </h1>
<h3>Click Item To View Description:<h3>

<ul>
  <% @items.each do |item| %>
    <li><%= link_to item.name, dept_item_path(@dept, item) %></li>
  <% end %>
</ul>
<br />
<%= link_to 'Create a new item', new_dept_item_path(@dept) %>
<br />
<%= link_to 'Back to Departments', depts_path %>

app/views/items/show.html.erb
<h1><%= @dept.category%><%=': ' =%><%= @item.name %> </h1>

<h4><%= "Description:" %><%=' '=%><%= @item.descr %></h4>
<h4><%= "Price:" %><%=' '=%><%= @item.price %></h4>



<br />
<%= link_to 'Edit Item', edit_dept_item_path([@dept, @item]) %>
<br />
<%= link_to 'Delete Item', dept_item_path(@dept, @item), method: :delete %>
<br />
<%= link_to 'Back to Department Items', dept_items_path(@dept) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeptStore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>